name: "Deye Data Collector"
version: "1.4.9"
slug: "voltron_deye"
description: "Collects data from Deye inverters via serial Modbus and exposes it via REST API."
url: "https://github.com/pr4u4t/deye-qt"
startup: "application"
boot: "auto"
documentation_url: "https://github.com/pr4u4t/deye-qt/blob/main/deye-data-collector/DOCS.md"
allow_multiple_instances: true
uart: true
services:
  - mqtt:need
arch:
  - aarch64
  - amd64

# Critical changes below for multi-instance support
options:
  instance_name: "Deye Instance ${INSTANCE}"  # Dynamic instance naming
  device: "/dev/ttyUSB0"
  baud: 9600
  parity: "none"
  data_bits: 8
  stop_bits: 1
  response_time: 1000
  number_of_retries: 3
  http_port: 8080  # Users will override this per instance
  http_server: false
  interval: 5000
  driver: "deye"
  mqtt_user: "user"
  mqtt_password: "password"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883

schema:
  instance_name: "str"
  device: "str"     # Users input unique devices (e.g., /dev/ttyUSB0, /dev/ttyUSB1)
  baud: "int"
  parity: "str"
  data_bits: "int"
  stop_bits: "int"
  response_time: "int"
  number_of_retries: "int"
  http_port: "int"  # Users must set unique ports (e.g., 8080, 8081)
  http_server: "bool"
  interval: "int"
  driver: "str"
  mqtt_user: "str"
  mqtt_password: "str"
  mqtt_host: "str"
  mqtt_port: "int"

privileged:
  - SYS_RAWIO
  - SYS_ADMIN

# Remove 'map: - config' (not needed for multi-instance)
devices:
  - "/dev:/dev:rwm"
ingress: false  # Disable ingress for multi-instance compatibility
image: "ghcr.io/pr4u4t/deye-qt"
data_dir: /data/${INSTANCE}

# Add ports configuration (critical for GUI instance management)
#ports:
#  "8080/tcp": "${http_port}"
