name: "Deye Data Collector"
version: "1.5.3"
slug: "voltron_deye"
description: "Collects data from Deye inverters via serial Modbus and exposes it via REST API."
url: "https://github.com/pr4u4t/deye-qt"
startup: "application"
boot: "auto"
documentation_url: "https://github.com/pr4u4t/deye-qt/blob/main/deye-data-collector/DOCS.md"
uart: true
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
options:
  inverters:
    - instance_name: "Inverter 1"
      device: "/dev/ttyUSB0"
      baud: 9600
      parity: "none"
      data_bits: 8
      stop_bits: 1
      response_time: 1000
      number_of_retries: 3
      driver: "deye"
      interval: 5000
  http_server: false
  http_port: 8080
  mqtt_user: "user"
  mqtt_password: "password"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
schema:
  inverters:
    - instance_name: "str"
      device: "str"
      baud: "int"
      parity: "str"
      data_bits: "int"
      stop_bits: "int"
      response_time: "int"
      number_of_retries: "int"
      driver: "str"
      interval: "int"
  http_server: "bool"
  http_port: "int"
  mqtt_user: "str"
  mqtt_password: "str"
  mqtt_host: "str"
  mqtt_port: "int"
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - config
devices:
  - "/dev:/dev:rwm"
ingress: true
image: "ghcr.io/pr4u4t/deye-qt"
data_dir: /data/${INSTANCE}
