name: "Deye Data Collector"
version: "1.3.9"
slug: "voltron_deye"
description: "Collects data from Deye inverters via serial Modbus and exposes it via REST API."
url: "https://github.com/pr4u4t/deye-qt"
startup: "application"
boot: "auto"
allow_multiple_instances: true
arch:
  - aarch64
  - amd64
  - arm64
options:
  instance_name: "Deye Instance 1"
  device: "/dev/ttyUSB0"
  baud: 9600
  parity: "none"
  data_bits: 8
  stop_bits: 1
  response_time: 1000
  number_of_retries: 3
  http_port: 8080
  http_server: false
  interval: 5000
schema:
  instance_name: "str"
  device: "str"
  baud: "int"
  parity: "str"
  data_bits: "int"
  stop_bits: "int"
  response_time: "int"
  number_of_retries: "int"
  http_port: "int"
  http_server: "bool"
  interval: "int"
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - config
devices:
  - "/dev:/dev:rwm"
ingress: true
image: "ghcr.io/pr4u4t/deye-qt:latest"

data_dir: /data/${INSTANCE}
