name: "Deye Data Collector"
version: "1.4.9"
slug: "voltron_deye"
description: "Collects data from Deye inverters via serial Modbus and exposes it via REST API."
url: "https://github.com/pr4u4t/deye-qt"
startup: "application"
boot: "auto"
documentation_url: "https://github.com/pr4u4t/deye-qt/blob/main/deye-data-collector/DOCS.md"
allow_multiple_instances: true
uart: true
services:
  - mqtt:need
arch:
  - aarch64
  - amd64
options:
  instance_name: "deye"  # Default instance name
  device: "/dev/ttyUSB0"
  baud: 9600
  parity: "none"
  data_bits: 8
  stop_bits: 1
  response_time: 1000
  number_of_retries: 3
  http_port: 8080
  http_server: false
  interval: 5000
  driver: "deye"
  mqtt_user: "user"
  mqtt_password: "password"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
schema:
  instance_name: "str"
  device: "device(subsystem=tty)"  # Better device selector
  baud: "int"
  parity: "list(none|odd|even)"
  data_bits: "int(7|8)"
  stop_bits: "int(1|2)"
  response_time: "int"
  number_of_retries: "int"
  http_port: "port"  # Use port type for validation
  http_server: "bool"
  interval: "int"
  driver: "str"
  mqtt_user: "str"
  mqtt_password: "password"
  mqtt_host: "str"
  mqtt_port: "port"
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
devices:
  - "/dev:/dev:rwm"
ingress: false
image: "ghcr.io/pr4u4t/deye-qt"
ports:
  "8080/tcp": "8080"
ports_description:
  "8080/tcp": "HTTP API port (customize per instance)"
