name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.pro'
      - '**/*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64, arm64, aarch64]  # Specify the architectures here

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up QEMU for cross-platform builds
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.architecture }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push the Docker image
      run: |
        docker buildx build --platform linux/${{ matrix.architecture }} --tag ghcr.io/pr4u4t/deye-qt:${{ matrix.architecture }} --push .

    - name: Tag the image with latest tag
      run: |
        docker tag ghcr.io/pr4u4t/deye-qt:${{ matrix.architecture }} ghcr.io/pr4u4t/deye-qt:latest
        docker push ghcr.io/pr4u4t/deye-qt:latest
